apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "traefik-forward-auth.fullname" . }}
  labels:
    {{- include "traefik-forward-auth.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "traefik-forward-auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "traefik-forward-auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "traefik-forward-auth.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- if .Values.forward_auth_config.provider.google }}
            - name: PROVIDERS_GOOGLE_CLIENT_ID
            {{- else if .Values.forward_auth_config.provider.oidc }}
            - name: DEFAULT_PROVIDER
              value: oidc
            - name: PROVIDERS_OIDC_ISSUER_URL
              value: {{ .Values.forward_auth_config.issuer.url }}
            - name: PROVIDERS_OIDC_CLIENT_ID
            {{- end }}
              value: {{ .Values.forward_auth_config.client.id }}
            {{- if .Values.forward_auth_config.provider.google }}
            - name: PROVIDERS_GOOGLE_CLIENT_SECRET
            {{- else if .Values.forward_auth_config.provider.oidc }}
            - name: PROVIDERS_OIDC_CLIENT_SECRET
            {{- end }}
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth-secrets
                  key: CLIENT_SECRET
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: traefik-forward-auth-secrets
                  key: SECRET
            - name: INSECURE_COOKIE
              value: {{ .Values.forward_auth_config.cookie.insecure | quote }}
            - name: COOKIE_DOMAIN
              value: {{ .Values.forward_auth_config.cookie.domain }}
            {{- if .Values.forward_auth_config.domain }}
            - name: DOMAIN
              value: {{ .Values.forward_auth_config.domain }}
            {{- end }}
            {{- if .Values.forward_auth_config.auth }}
            - name: AUTH_HOST
              value: {{ .Values.ingress.host }}
            {{- end }}
          ports:
            - name: http
              containerPort: 4181
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
