apiVersion: v1
kind: Secret
metadata:
  name: {{ include "traefik-forward-auth.fullname" . }}
  labels:
    {{- include "traefik-forward-auth.labels" . | nindent 4 }}
type: Opaque
data:
  CLIENT_SECRET: {{ required "OIDC client secret is required" .Values.forward_auth_config.client_secret | b64enc }}
  SECRET: {{ required "Cookie signing secret is required" .Values.forward_auth_config.secret | b64enc }}
