kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: traefik-forward-auth-ingress
  namespace: core
  annotations:
    kubernetes.io/ingress.class: traefik-external
    ingress.kubernetes.io/content-security-policy: default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline';
    ingress.kubernetes.io/content-type-nosniff: "true"
    ingress.kubernetes.io/force-hsts: "true"
    ingress.kubernetes.io/frame-deny: "true"
    ingress.kubernetes.io/hsts-max-age: "315360000"
    ingress.kubernetes.io/protocol: http
    ingress.kubernetes.io/referrer-policy: strict-origin
    kubernetes.io/ingress.class: traefik-external
    traefik.ingress.kubernetes.io/preserve-host: "true"
spec:
  rules:
    - host: {{ .Values.deployment.auth.host_url }}
      http:
        paths:
          - backend:
              serviceName: traefik-forward-auth
              servicePort: {{ .Values.port | default "80" }}
