kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: traefik-forward-auth-ingress
  namespace: core
  annotations:
spec:
  rules:
    - host: {{ .Values.deployment.auth.host_url }}
      http:
        paths:
          - backend:
              serviceName: traefik-forward-auth
              servicePort: {{ .Values.port | default "80" }}
